name: seqampc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=3
  - alsa-lib=1.2.15.3
  - ampl-asl=1.0.0
  - aom=3.12.1
  - blas=2.305
  - blas-devel=3.11.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - casadi=3.7.0
  - certifi=2026.1.4
  - contourpy=1.3.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - ipopt=3.14.19
  - joblib=1.5.2
  - jpeg=9f
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libavif=1.1.1
  - libblas=3.11.0
  - libblasfeo=0.1.4.2
  - libcblas=3.11.0
  - libclang13=21.1.8
  - libcups=2.4.2
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.3
  - libfatrop=0.0.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libkrb5=1.21.3
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm15=15.0.7
  - libllvm21=21.1.8
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libopus=1.6.1
  - libosqp=1.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libqdldl=0.1.8
  - libre2-11=2024.07.02
  - libscotch=7.0.4
  - libsodium=1.0.20
  - libspral=2025.05.20
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libvpx=1.13.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxkbfile=1.1.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - lzip=1.21
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mesalib=25.1.5
  - metis=5.1.0
  - mkl=2025.3.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.2
  - mkl_random=1.3.1
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - ncurses=6.5
  - nspr=4.38
  - nss=3.118
  - numpy-base=2.4.1
  - openblas=0.3.30
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.1
  - pandas=3.0.0
  - pcre2=10.46
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pyside6=6.9.2
  - python=3.13.9
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtshadertools=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebengine=6.9.2
  - qtwebsockets=6.9.2
  - re2=2024.07.02
  - readline=8.3
  - scikit-learn=1.7.2
  - scipy=1.17.0
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.1
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.5.0
  - tikzplotlib=0.10.1
  - tinyxml2=11.0.0
  - tk=8.6.15
  - tornado=6.5.4
  - tqdm=4.67.1
  - tzdata=2025b
  - wayland=1.24.0
  - webcolors=1.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - charset-normalizer==3.4.4
      - cycler==0.12.1
      - deprecated==1.3.1
      - fire==0.7.1
      - flatbuffers==25.9.23
      - fonttools==4.61.1
      - future-fstrings==1.2.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - numpy==2.4.2
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==26.0
      - pillow==12.1.1
      - pip==24.3.1
      - protobuf==6.33.1
      - pygments==2.19.2
      - pyparsing==3.3.2
      - requests==2.32.5
      - rich==14.2.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - tf-keras==2.20.1
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==2.0.1
